name: Build llama.cpp with BLIS Backend for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Install dependencies
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git cmake wget unzip

    # 3. Install Android SDK and NDK (Add your requested commands here)
    - name: Install Android SDK and NDK
      run: |
        cd ~
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip && \
        unzip commandlinetools-linux-8512546_latest.zip && \
        mkdir -p ~/android-sdk/cmdline-tools && \
        mv cmdline-tools latest && \
        mv latest ~/android-sdk/cmdline-tools/ && \
        rm -rf commandlinetools-linux-8512546_latest.zip

        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "ndk;26.3.11579264"

    # 4. Set up environment for Android NDK
    - name: Set up Android NDK environment
      run: |
        export ANDROID_NDK=$HOME/android-sdk/ndk/26.3.11579264
        export PATH=$ANDROID_NDK:$PATH
        echo "ANDROID_NDK=$ANDROID_NDK" >> $GITHUB_ENV
        echo "PATH=$PATH" >> $GITHUB_ENV

    # 5. Clone and build BLIS for Android
    - name: Clone and build BLIS for Android
      run: |
        git clone --recursive https://github.com/flame/blis.git
        cd blis && ./configure --enable-cblas -t openmp,pthreads auto
        make -j
        sudo make install

    # 6. Build llama.cpp with BLIS support for Android
    - name: Build llama.cpp with BLIS support for Android
      run: |
        git clone https://github.com/ggml-org/llama.cpp.git
        cd llama.cpp
        mkdir build
        cd build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DGGML_BLAS=ON \
          -DGGML_BLAS_VENDOR=FLAME \
          -DANDROID_PLATFORM=android-21 \
          -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)

    # 7. Package and upload binaries for Android
    - name: Package binaries for Android
      run: |
        zip -r llama-blis-android.zip ~/llama.cpp/build/bin

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: llama-blis-android
        path: llama-blis-android.zip
