name: Build llama.cpp with OpenCL (CLBlast) on Ubuntu 22.04

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-opencl:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake ninja python3 git

    - name: Install SDK
      run: |
        cd ~
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip && \
        unzip commandlinetools-linux-8512546_latest.zip && \
        mkdir -p ~/android-sdk/cmdline-tools && \
        mv cmdline-tools latest && \
        mv latest ~/android-sdk/cmdline-tools/ && \
        rm -rf commandlinetools-linux-8512546_latest.zip

        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "ndk;26.3.11579264"

    - name: Install OpenCL Headers and Library
      run: |
        mkdir -p ~/dev/llm
        cd ~/dev/llm

        git clone https://github.com/KhronosGroup/OpenCL-Headers && \
        cd OpenCL-Headers && \
        cp -r CL ~/android-sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include

        cd ~/dev/llm

        git clone https://github.com/KhronosGroup/OpenCL-ICD-Loader && \
        cd OpenCL-ICD-Loader && \
        mkdir build_ndk26 && cd build_ndk26 && \
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_TOOLCHAIN_FILE=$HOME/android-sdk/ndk/26.3.11579264/build/cmake/android.toolchain.cmake \
          -DOPENCL_ICD_LOADER_HEADERS_DIR=$HOME/android-sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=24 \
          -DANDROID_STL=c++_shared && \
        ninja && \
        cp libOpenCL.so ~/android-sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android

    - name: Build llama.cpp
      run: |
        cd ~/dev/llm

        git clone https://github.com/ggml-org/llama.cpp && \
        cd llama.cpp && \
        mkdir build-android && cd build-android

        cmake .. -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE=$HOME/android-sdk/ndk/26.3.11579264/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-28 \
          -DBUILD_SHARED_LIBS=OFF \
          -DGGML_OPENCL=ON

        ninja
  
    - name: Package binaries
      run: |
        zip -r llama-opencl-build.zip ~/dev/llm/llama.cpp/build-android

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: llama-opencl-build
        path: llama-opencl-build.zip
